server:
  port: 18081
spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
  datasource:
    url: jdbc:mysql://192.168.14.235:33007/sql_optimization?useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: yyxt
    password: Jlopfhs!#15jkfedata
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 60000
      idle-timeout: 600000
      max-lifetime: 1800000